FROM docker.io/alpine:3.21
RUN apk add --no-interactive \
            bash \
            binutils-riscv-none-elf \
            coreutils \
            gcc-riscv-none-elf \
            git \
            make \
            python3 \
            qemu-system-riscv64 \
            tar \
            zstd

