# SPDX-FileCopyrightText: 2025 ukoOS Contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

FROM docker.io/alpine:3.21
RUN apk add --no-interactive \
            bash \
            binutils-riscv-none-elf \
            busybox-extras \
            coreutils \
            gcc-riscv-none-elf \
            gdb-multiarch \
            git \
            make \
            mdbook \
            minicom \
            openssh \
            perl \
            python3 \
            qemu-system-riscv64 \
            reuse \
            tar \
            zstd
