name: Build ukoOS
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: 'ubuntu-latest'
    container:
      image: docker.io/alpine:3.21
    steps:
      - name: Install dependencies
        run: |
          apk add --no-interactive \
            bash \
            binutils-riscv-none-elf \
            coreutils \
            gcc-riscv-none-elf \
            git \
            make \
            mdbook \
            perl \
            python3 \
            qemu-system-riscv64 \
            tar \
            zstd
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          git config --global --add safe.directory .
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          shortrev=$(git rev-parse --short HEAD)
          mkdir build
          cd build
          ../configure
          make -j$(nproc) -l$(nproc)
          mkdir ukoos-git-$shortrev
          make DESTDIR=$(realpath ukoos-git-$shortrev) install
          tar --create --file ukoos-git-$shortrev.tar \
            --format posix \
            --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
            --mtime "@$SOURCE_DATE_EPOCH" \
            --sort name \
            --owner 0 --group 0 --numeric-owner \
            ukoos-git-$shortrev
          zstd -19 --threads=0 ukoos-git-$shortrev.tar
          sha256sum ukoos-git-$shortrev.tar ukoos-git-$shortrev.tar.zst
          cp ukoos-git-$shortrev.tar.zst ../ukoos-git.tar.zst
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ukoos-git.tar.zst
          path: ukoos-git.tar.zst
          compression-level: 0
  build-dev-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: ukoos
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: |
          nix build -L .#dev-image-milkv-duos
          cp result/sdcard.img dev-image-milkv-duos-sdcard.img
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-image-milkv-duos-sdcard.img
          path: dev-image-milkv-duos-sdcard.img
