# SPDX-FileCopyrightText: ukoOS Contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build ukoOS
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: 'ubuntu-latest'
    container:
      image: docker.io/alpine:3.23
    strategy:
      matrix:
        compiler:
          - clang
          - gcc
        target:
          - milkv-duos
          - milkv-jupiter
          - qemu-riscv64
    steps:
      - name: Install dependencies
        run: |
          apk add --no-interactive \
            bash \
            binutils-riscv-none-elf \
            coreutils \
            gcc-riscv-none-elf \
            gdb-multiarch \
            git \
            make \
            mdbook \
            perl \
            python3 \
            qemu-system-riscv64 \
            tar \
            zstd
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          git config --global --add safe.directory .
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          shortrev=$(git rev-parse --short HEAD)
          mkdir build
          cd build
          [ ${{ matrix.compiler }} == "clang" ] && ../configure --target ${{ matrix.target }} --clang || ../configure --target ${{ matrix.target }}
          make -j$(nproc) -l$(nproc)
          name=ukoos-${{ matrix.target }}-git-$shortrev
          mkdir $name
          make DESTDIR=$(realpath $name) install
          tar --create --file $name.tar \
            --format posix \
            --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
            --mtime "@$SOURCE_DATE_EPOCH" \
            --sort name \
            --owner 0 --group 0 --numeric-owner \
            $name
          zstd -19 --threads=0 $name.tar
          sha256sum $name.tar $name.tar.zst
          cp $name.tar.zst ../ukoos-${{ matrix.target }}-git.tar.zst
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ukoos-${{ matrix.target }}-git.tar.zst
          path: ukoos-${{ matrix.target }}-git.tar.zst
          compression-level: 0
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: ukoos
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run checks
        run: |
          nix flake check -L
      - name: Build images
        run: |
          nix build -L .#all-images
      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: result/
