name: Deploy documentation
on:
on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk
jobs:
  build:
    runs-on: 'ubuntu-latest'
    container:
      image: docker.io/alpine:3.21
    steps:
      - name: Install dependencies
        run: |
          apk add --no-interactive \
            bash \
            binutils-riscv-none-elf \
            coreutils \
            gcc-riscv-none-elf \
            gdb-multiarch \
            git \
            make \
            mdbook \
            perl \
            python3 \
            qemu-system-riscv64 \
            tar \
            zstd
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docs
        run: |
          mkdir build
          cd build
          ../configure --target qemu-riscv64
          make doc/book
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/doc/book
  deploy-pages:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
